name: Generate JSON
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Setup Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub

      - name: Generate JSON
        run: |
          export GIT_TOKEN="${{ secrets.AUTH_KEY }}"
          python generate.py "${{ secrets.GITHUB_TOKEN }}" > modules.json

      - name: Commit Changes
        run: |
          git config --global user.email "manuel.merkl@proton.me"
          git config --global user.name "s3tupw1zard"
          git add modules.json
          git commit -sm "Update modules.json" || true
          git push || true
